[project]
name = "devops-telemetry-app"
version = "0.1.0"
description = "Laptop telemetry publisher for DevOps module"
dependencies = [
    "psutil>=5.9.0",
    "paho-mqtt>=1.6.1",
]

[tool.uv]
package = false
